apiVersion: v1
kind: Service
metadata:
  name: backend
  labels:
    app: backend
spec:
  selector:
    app: backend
  ports:
    - name: metrics
      port: 8081
      targetPort: backendport
  type: LoadBalancer
  
---

apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: backend
  namespace: monitoring
  labels:
    app: backend
    release: prometheus
spec:
  selector:
    matchLabels:
      app: backend
  endpoints:
  - port: metrics
    path: /metrics
    interval: 15s
  namespaceSelector:
    matchNames:
    - default



apiVersion: v1
kind: Service
metadata:
  namespace: monitoring
  name: backend-metrics
  labels:
    app: backend-metrics
spec:
  ports:
    - name: metrics
      port: 8081
      protocol: TCP
      targetPort: backendport
  selector:
    app: backend
    


apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  namespace: monitoring
  name: backend
  labels:
    component: backend
    prometheus: kube-prometheus
spec:
  endpoints:
    - interval: 15s
      port: metrics
      path: /metrics
  jobLabel: component
  namespaceSelector:
    matchNames:
    - backend
  selector:
    matchLabels:
      app: backend-metrics